Super cleaned bin scripts

diff --git a/zsh/.config/aliasrc b/zsh/.config/aliasrc
--- a/zsh/.config/aliasrc
+++ b/zsh/.config/aliasrc
@@ -2,52 +2,102 @@
 
 # Extract archives with ex
 ex () {
-  if [ -f $1 ] ; then
+  if [ -f "$1" ] ; then
     case $1 in
-      *.tar.bz2)   tar xjf $1   ;;
-      *.tar.gz)    tar xzf $1   ;;
-      *.bz2)       bunzip2 $1   ;;
-      *.rar)       unrar x $1   ;;
-      *.gz)        gunzip $1    ;;
-      *.tar)       tar xf $1    ;;
-      *.tbz2)      tar xjf $1   ;;
-      *.tgz)       tar xzf $1   ;;
-      *.zip)       unzip $1 -d "${1%%.*}";;
-      *.Z)         uncompress $1;;
-      *.7z)        7z x $1      ;;
-      *.deb)       ar x $1      ;;
-      *.tar.xz)    tar xf $1    ;;
-      *.tar.zst)   unzstd $1    ;;
-      *)           echo "'$1' cannot be extracted via ex()" ;;
+      *.tar.bz2)   tar xjf "$1"   ;;
+      *.tar.gz)    tar xzf "$1"   ;;
+      *.bz2)       bunzip2 "$1"   ;;
+      *.rar)       unrar x "$1"   ;;
+      *.gz)        gunzip "$1"    ;;
+      *.tar)       tar xf "$1"    ;;
+      *.tbz2)      tar xjf "$1"   ;;
+      *.tgz)       tar xzf "$1"   ;;
+      *.zip)       unzip "$1" -d "${1%%.*}";;
+      *.Z)         uncompress "$1";;
+      *.7z)        7z x "$1"      ;;
+      *.deb)       ar x "$1"      ;;
+      *.tar.xz)    tar xf "$1"    ;;
+      *.tar.zst)   unzstd "$1"    ;;
+      *)           echo "$1 cannot be extracted via ex()" ;;
     esac
   else
     echo "'$1' is not a valid file"
   fi
 }
 
+# Move a file to a new location and put a symlink where it used to be
+mvln () {
+    mv -- "$1" "$2"
+    ln -s -- "$2" "$1"
+}
+
+# Use fzf to select usb device and show info
+usbinfo () {
+    if ! which fzf >/dev/null 2>&1; then
+        echo "Please install fzf"
+        exit
+    fi
+    lsusb | fzf | awk '{print $6}' | xargs -I {} lsusb -v -d "{}"
+}
+
+http2ssh () {
+    REMOTE=$(git remote -v | grep fetch | awk '{print $2}')
+    USER=$(echo "$REMOTE" | awk -F/ '{print $4}')
+    REPO=$(echo "$REMOTE" | awk -F/ '{print $5}')
+
+    echo "Current remote URL is: $REMOTE"
+
+    # Switch to ssh, otherwise do noting
+    case $REMOTE in
+        *"https"*)
+            # Echo relevant info to user
+            echo "USER=$USER"
+            echo "REPO=$REPO"
+            echo "New URL is git@github.com:$USER/$REPO"
+            git remote set-url origin "git@github.com:$USER/$REPO"
+            echo "Changed to SSH."
+            ;;
+        *)
+            echo "No change made, already using SSH."
+            ;;
+    esac
+}
+
 # This function will:
 # 1) auto-cd if given a directory instead of a file
 # 2) Automatically request root permissions if the user isn't able to modify the file
 # It's a small QOL improvement since I always use vim on a directory or root file.
-#vim () {
-    ## Cd to directory if it doesn't exist
-    #if [ -d "$1" ]; then
-        #cd "$1" || exit
-    ## If it's a file
-    #elif [ -f "$1" ]; then
-        ## open normally if user has privileges
-        #if groups | grep -q "$(stat -c "%G" "$1")"; then
-            #nvim "$1"
-        ## otherwise open with root
-        #else
-            #sudo nvim "$1"
-        #fi
-    ## If the file doesn't exist, create it
-    #else
-        #nvim "$1"
-    #fi
-#}
+vim () {
+    # Cd to directory if it doesn't exist
+    if [ -d "$1" ]; then
+        cd "$1" || exit
+    # If it's a file
+    else
+        # open normally if user has privileges
+        if groups | grep -q "$(stat -c "%G" "$1")"; then
+            nvim "$1"
+        # otherwise open with root
+        else
+            sudo -E nvim "$1"
+        fi
+    fi
+}
 
+sshkey() {
+    input="$1"
+    if ssh $input "test -e $HOME/.ssh/authorized_keys"; then
+        echo "File exists"
+    else
+        echo "Creating file"
+            ssh "$1" "mkdir -p $HOME/.ssh && touch $HOME/.ssh/authorized_keys"
+    fi
+    if [[ -n "$input" ]]; then
+        cat "$HOME/.ssh/id_rsa.pub" | ssh "$input" >> 'cat >> ~/.ssh/authorized_keys'
+        echo "Appending key to remote's authorized keys"
+    else
+        echo "usage: sshkey [user@IP]"
+    fi
+}
 
 # Shorten name
 alias mutt='neomutt'
